import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";
import SignIn from "../../components/SignIn";
import SIdebar from "../../components/SIdebar";

export default function Home() {
  const { data: session } = useSession();
  if (!session) return <SignIn />;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-[1400px] mx-auto">
        <SIdebar />
      </main>
    </>
  );
}
